version: "3.8"

services:

  backend:
    image: backend
    build:
      context: ./Backend/odc
      dockerfile: Dockerfile
    ports:
      - 8082:8000
    environment:
      - DJANGO_SETTINGS_MODULE=odc.settings
      - POSTGRES_HOST=database
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: odc
      POSTGRES_PASSWORD: odc123
      POSTGRES_DB: odcdb
    volumes:
      - pgdata:/var/lib/postgresql/database

  db-migrations:
    image: backend
    command: python manage.py migrate
    depends_on:
      - database
    profiles:
      - tools

  frontend:
    image: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend
    prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:
  pgdata:
    driver: local
